spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # entity? ???? ??? ???? ??? ??. ??? create? ???? ??? update? ??? ??? ??.
      naming:
        #      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy database table ? ??? ??? ? ????? ???? ??? ??? ???? ?? ??? ??.# userName => user_name

        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

    jackson:
      serialization:
        fail-on-empty-beans: false
  devtools:
    livereload:
      enabled: true